quarkus.http.port=8080

# CORS — permite o React (localhost e Vercel) chamar a API
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,https://*.vercel.app
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.username=rm568419
quarkus.datasource.password=250204
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
